[phases.setup]
nixPkgs = ["python310", "gcc"]

[phases.install]
cmds = ["python -m venv .venv", ". .venv/bin/activate", "pip install -r requirements.txt"]

[phases.build]
cmds = ["pip install --upgrade pip"]

[start]
cmd = "gunicorn backend_phyton.wsgi"