[phases.setup]
nixPkgs = ["python310", "python310Packages.pip", "python310Packages.setuptools", "gcc"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "gunicorn backend_phyton.wsgi"