# Generated by Django 5.1.5 on 2025-03-20 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userbookrecommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbookrecommendation',
            name='preview_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
