# Generated by Django 5.0.8 on 2025-04-01 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_bookrecommendation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookRecommendation',
        ),
    ]
