# Generated by Django 5.1.5 on 2025-03-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userbookrecommendation_preview_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbookrecommendation',
            name='preview_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
