# Generated by Django 5.1.5 on 2025-04-19 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_readinghistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserBookRecommendation',
        ),
    ]
