# Generated by Django 5.1.5 on 2025-04-22 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_delete_userbookrecommendation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='profile_picture',
        ),
    ]
